### ISSUE TITLE
lint errors

### ISSUE THREAD

**Issue by kwaimind** [rossoskull/ReactJS-Todo-App#4]
Suggest `/src/Components/AddTodo.js` and `/src/App.js` are run through a js lint to fix stylistic mistakes.

**Comment by rossoskull** [comment]
Will you be solving this issue?

**Comment by kwaimind** [comment]
Sure thing. Leave it with me.

**Comment by rossoskull** [comment]
Okay :tada:

**Comment by rsm23** [comment]
@rossoskull please check #6 all lint issues are fixed too
